[package]
name = "serial-monitor-rust"
version = "0.3.3"
edition = "2021"
authors = ["Linus Leo Stöckli"]
description = "Serial Monitor and Plotter written in rust."
license = "GPL-3.0"
homepage = "https://github.com/hacknus/serial-monitor-rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3"
eframe = { version = "0.30.0", features = ["persistence", "wayland", "x11"] }
egui_plot = "0.30.0"
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
egui-phosphor = { version = "0.8.0" }
egui-theme-switch = { version = "0.2.3", default-features = true }
egui_logger = { git = "https://github.com/hacknus/egui_logger" }
egui-file-dialog = { version = "0.8.0", git = "https://github.com/hacknus/egui-file-dialog", branch = "sort_by_metadata", features = ["information_view"] }
image = { version = "0.25", default-features = false, features = ["png"] }
keepawake = { version = "0.5.1" }
preferences = { version = "2.0.0" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serialport = { version = "4.6.1", features = ["serde"] }
log = "0.4.22"

[package.metadata.bundle]
name = "Serial Monitor"
identifier = "com.hacknus.serial_monitor"
icon = ["./icons/install.png"]
version = "0.3.3"
copyright = "Copyright (c) hacknus 2023. All rights reserved."
category = "Developer Tool"
short_description = "Serial Monitor and Plotter written in rust."
license = "GPL-3.0"
osx_minimum_system_version = "10.8"
osx_url_schemes = ["com.hacknus.serial_monitor"]

[package.metadata.wix]
dbg-build = false
dbg-name = false
name = "Serial Monitor"
no-build = false
output = "target/wix/SerialMonitorInstaller.msi"
version = "0.3.3"
license = "GPL-3.0"