name: Deployment

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: windows-2019
            target: x86_64-pc-windows-msvc
          - os: windows-2019
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libudev-dev && cargo install cargo-bundle

      - name: Install Dependencies (macOS)
        if: contains(matrix.os, 'macos')
        run: cargo install cargo-bundle

      - name: Install Dependencies (Windows)
        if: contains(matrix.os, 'windows')
        run: cargo install --force cargo-wix

      - name: Build
        run: cargo build --features self_update --release

      - name: Compress Output (Linux & macOS)
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: |
          cd target/release
          zip -r serial-monitor-${{ matrix.target }}.zip *

      - name: Compress Output (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          Compress-Archive -Path target/release/* -DestinationPath serial-monitor-${{ matrix.target }}.zip

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/serial-monitor-${{ matrix.target }}.zip
          asset_name: serial-monitor-${{ matrix.target }}.zip
          asset_content_type: binary
